INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Aperol 750ml ','Aperol ',0.0,4,11,'00023_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Campari Aperitivo 450ml ','Campari ',0.0,4,11,'00014_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Campari Aperitivo 750ml','Campari ',0.0,4,11,'00005_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Campari tonic + copon ','Campari Tonic ',0.0,5,11,'00006_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Carpano Rosso 950ml ','Carpano Rosso',0.0,3,11,'00013_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Cinzano Prosecco 750ml','Cinzano Prosecco',0.0,4,11,'00007_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Cinzano Rosso 950ml','Cinzano Rosso',0.0,3,11,'00016_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cynar Aperitivo 750ml','Cynar Aperitivo ',0.0,3,11,'00017_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Doctor Lemon Lata 473ml',' Doctor Lemon',0.0,4,11,'00018_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Gancia Frutos Rojos 750ml Botella ','Gancia ',0.0,2,11,'00008_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Gancia Sprintz 750ml Botella','Gancia ',0.0,3,11,'00003_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Gancia 950lts Botella','Gancia ',0.0,3,11,'00002_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Hesperidina 750ml Botella','Hesperidina ',0.0,4,11,'00009_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Jagermeister 750cc Botella','Jagermeister',0.0,5,11,'00010_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Jerez Crotta 750ml Botella','Jerez Crotta ',0.0,3,11,'00021_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Martini Bianco 1000cc Botella','Martini ',0.0,3,11,'00011_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Martini Extra Dry 950ml Botella','Martini ',0.0,3,11,'00004_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Martini Rosso 1000cc','Martini ',0.0,3,11,'00012_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Aperitivo Oporto Crotta 750ml','Oporto Crotta ',0.0,2,11,'00020_aperitivo','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Angostura Bitter 200ml ','Angostura Bitter ',0.0,5,13,'00001_ANGOSTURA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Angostura Bitter Orange 100ml ','Angostura Bitter ',0.0,5,13,'00003_ANGOSTURA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Angostura Bitter 100ml','Angostura Bitter ',0.0,5,13,'00002_ANGOSTURA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Bavaria 8,6 Black Lata 500ml','Bavaria ',0.0,4,2,'00005_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Bavaria 8,6 Original Lata 500ml ','Bavaria ',0.0,4,2,'00007_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Amstel Litro Botella Retornable','Amstel ',0.0,4,2,'00001_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Amstel Lata 473ml ','Amstel ',0.0,4,2,'00002_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Amstel Lager Lata 473ml ','Amstel ',0.0,4,2,'00003_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Andes Ipa Lata 473ml ','Andes',0.0,4,2,'00011_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Andes Negra Lata 473ml','Andes',0.0,4,2,'00012_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Andes Roja Lata 473ml ','Andes',0.0,4,2,'00013_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Andes Rubia Lata 473ml ','Andes',0.0,4,2,'00014_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Atlantica Lata 473ml','Antares ',0.0,4,2,'000015_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Honey Lata 473ml','Antares ',0.0,4,2,'00017_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Ipa Lata 473ml','Antares ',0.0,4,2,'00018_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Kolsch Botella 500ml','Antares ',0.0,4,2,'00019_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Lata Caravana 473ml','Antares ',0.0,4,2,'00016_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Playa Grande Botella 500ml','Antares ',0.0,4,2,'00020_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Porter Botella 500ml','Antares ',0.0,4,2,'117_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Antares Scotch Botella 500 ml','Antares ',0.0,4,2,'00021_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Arsenalnoye cooler Botella 470ml','Arsenalnoye',0.0,4,2,'00022_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Bear Beer Dark Wheat ','Bear Beer',0.0,5,2,'00023_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Bear Beer Lager','Bear Beer',0.0,5,2,'00024_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Bear Beer Stout','Bear Beer',0.0,5,2,'00025_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Bear Beer Wheat ','Bear Beer',0.0,5,2,'00026_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Blue Moon Porron x 355 ml','Blue Moon',0.0,5,2,'00027_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Boris Slam x 500 ml ','Boris',0.0,5,2,'00028_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Budweiser Lata x 473 ml ','Budweiser ',0.0,4,2,'00033_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Budweiser 710 ml ','Budweiser ',0.0,4,2,'00034_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Buenos Vientos Irish Red ','Buenos Vientos',0.0,4,2,'00035_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Buenos Vientos Porter ','Buenos Vientos',0.0,4,2,'119_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cachalote American Ipa','Cachalote',0.0,4,2,'00036_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cachalote Golden x 473ml','Cachalote',0.0,4,2,'120_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cachalote Porter 473ml','Cachalote',0.0,4,2,'00038_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cachalote Scottish Export X 473m','Cachalote',0.0,4,2,'00039_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cachalote Session Ipa 473ml','Cachalote',0.0,4,2,'00037_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cachingo 473ml Amber','Cachingo',0.0,4,2,'00040_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cachingo 473ml Pale ','Cachingo',0.0,4,2,'00041_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Corona x 269 ml Lata ','Corona',0.0,5,2,'59_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Corona x 710 ml Botella','Corona',0.0,5,2,'00029_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cusqueña Golden Lar 330 Ml.','Cusqueña',0.0,5,2,'00030_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cusqueña Golden x 473 ml Lata','Cusqueña',0.0,5,2,'60_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cusqueña Red Lager 330 Ml.','Cusqueña',0.0,5,2,'00032_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Cusqueña Trigo 330 Ml.','Cusqueña',0.0,5,2,'118_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Dab Dark Beer x 500 ml','Dab',0.0,5,2,'61_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Duff x 330 ml Lata ','Duff',0.0,5,2,'00004_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('CervezaGrolsch x 473 ml Lata','Grolsch',0.0,4,2,'63_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Grolsh Tapa Ceramica 450 ml','Grolsch',0.0,4,2,'115_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Imperial Amber Lager x 1 Lts Retornable','Imperial',0.0,5,2,'00009_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cerveza Patagonia 24.7 x 730 ml Botella ','Patagonia',0.0,5,2,'00031_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Alaskasha Gin 750 ml ','Alaskasha',0.0,2,4,'3','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Monkey 47 Schwarzwald Dry Gin 500 ml','Monkey 47',0.0,5,4,'1','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Beeffeater botella 750 ml','Beeffeater',0.0,5,4,'3_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Beeffeater Pink botella 750 ml','Beeffeater',0.0,5,4,'2_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Beeffeater 24 London Dry Gin botella 750 ml ','Beeffeater',0.0,5,4,'1_GIN','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Bombay London botella 750 ml','Bombay',0.0,5,4,'4_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Brokers London Dry botella 750 ml','Brokers',0.0,5,4,'5_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin BullDog Longon Dry botella 750 ml','BullDog',0.0,5,4,'6_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Hilbing London Dry botella 750 ml','Hilbing',0.0,5,4,'7_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Hilbing Malbec botella 750 ml','Hilbing',0.0,5,4,'8_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Gennaro Artesanal 750 ml','Gennaro',0.0,4,4,'13','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Gennaro estuche ml','Gennaro',0.0,4,4,'00004_GINEBRA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin La Buenos Aires botella 750 ml','La Buenos Aires',0.0,5,4,'9_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin La Salvaje Rojo botella 750 ml','La Salvaje',0.0,5,4,'13_GIN','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin La Salvaje Verde botella 750 ml','La Salvaje',0.0,5,4,'11_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Mare botella 700 ml','Mare ',0.0,5,4,'12_gin','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Portela Me Mata Limon botella botella 750 ml','Portela',0.0,2,4,'4','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Portela Miss Saigon Te Jazmin 750 ml','Portela',0.0,2,4,'2','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Restinga Destilado Otoño 750 ml','Restinga',0.0,4,4,'5','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Ribera 750 ml','Ribera',0.0,3,4,'6','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Tanqueray botella 750 ml','Tanqueray',0.0,5,4,'00003_GINEBRA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Tanqueray Nº Ten 1000 ml','Tanqueray',0.0,5,4,'7','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin The botanist Islay botella 750 ml','The botanist',0.0,5,4,'8','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Gordons botella 750 ml ','Gordons',0.0,4,4,'9','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Hendrick botella 700 ml','Hendrick',0.0,5,4,'10','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Principe de los Apostoles botella 700 ml','Principe de los Apostoles',0.0,3,4,'11','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Star Of Bombay botella 750 ml','Star Of Bombay',0.0,5,4,'12','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin Sur','Sur ',0.0,5,4,'00001_GINEBRA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gin & tonic ','Tonic',0.0,5,4,'00002_GINEBRA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Amareto Lazzaroni Authentic 750 ml','Lazzaroni',0.0,5,5,'01_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Lazzaroni Amareto & Peach Liqueur','Lazzaroni ',0.0,5,5,'06_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor 8 Hermanos 1000cc','8 Hermanos',0.0,3,5,'03_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Disaronno 700 ml','Disaronno',0.0,5,5,'05_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Amarula 750 ml','Amarula',0.0,4,5,'07_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Bols Casis botella 700 cc','Bols',0.0,2,5,'09_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Bols Chocolate Blanco ','Bols',0.0,2,5,'15_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Bols Dulce de Leche','Bols',0.0,2,5,'10_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Bols Frutilla','Bols',0.0,2,5,'11_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Bols Triple Sec botella 700 ml','Bols',0.0,2,5,'13_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Borghetti cafe botella 700 ml','Borghetti',0.0,3,5,'14_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cointreau botella 750 cc','Cointreau',0.0,5,5,'17_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cointreau Noir Orange Liqueur botella ','Cointreau',0.0,5,5,'16_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Drambui botella 750 ml','Drambui',0.0,4,5,'23_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cusenier Blue Curacao botella','Cusenier',0.0,2,5,'18_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cusenier Durazno botella','Cusenier',0.0,2,5,'19_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cusenier Frutilla botella','Cusenier',0.0,2,5,'20_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cusenier Melon botella','Cusenier',0.0,2,5,'21_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cusenier Lemoncello botella','Cusenier',0.0,2,5,'02_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Cusenier Menta','Cusenier',0.0,2,5,'22_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Limoncello Luxuardo Italiano botella 750 ml','Limoncello',0.0,4,5,'24_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Malibu botella 750 ml','Malibu',0.0,3,5,'25_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Sheridans botella 750 ml','Sheridans',0.0,4,5,'26_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Licor Tia Maria botella 690 ml ','Tia Maria',0.0,2,5,'27_licor','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('La Posta Paulecci Malbec x 750 ml','La Posta',0.0,3,12,'00001_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('La Posta Glorieta Pinot Noir x 750 ml ','La Posta',0.0,3,12,'00002_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Luigi Bosca de Sangre x 750 ml','Luigi Bosca',0.0,4,12,'00004_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Luigi Bosca Gala x 750 ml','Luigi Bosca',0.0,4,12,'00003_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Luigi Bosca Cabernet Sauvignon ','Luigi Bosca',0.0,3,12,'00005_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Trumpeter Malbec Reserve x 750 ml','Trumpeter',0.0,3,12,'00006_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Trumpeter Cabernet Sauvignon x 750 ml','Trumpeter',0.0,3,12,'00007_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Trumpeter Reserve Torrontes x 750 ml ','Trumpeter',0.0,3,12,'00008_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('La Linda Sweet Viognier x 750 ml','La Linda',0.0,3,12,'00009_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('La Linda Old Vines Malbec x 750 ml ','La',0.0,3,12,'00010_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('La Linda High Vines Sauvignon Blanc x 750 ml','La Linda',0.0,3,12,'00011_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('La Linda Cabernet Sauvignon x 750 ml','La Linda',0.0,3,12,'00012_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Nicola Catena Bonarda x 750 ml','Nicola ',0.0,5,12,'00013_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('D.V Catena Malbec Malbec x 750 ml','D.V Catena',0.0,4,12,'00014_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Gran Alma Negra 2014','Alma Negra',0.0,5,12,'00015_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Alma Negra Crange x 750 ml ','Alma Negra',0.0,4,12,'00016_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Luca Old Vine Malbec x 750 ml','Luca ',0.0,4,12,'00017_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Luca Laborde Double Select Syrah x 750 ml','Luca',0.0,4,12,'00019_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Luca Beso de Dante x 750 ml','Luca',0.0,4,12,'00018_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Angelica Zapata Malbec Alta x 750 ml','Angelica Zapata',0.0,5,12,'00021_CERVEZA','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Angelica Zapata Cabernet Sauvignon Alta x 750 ml ','Angelica Zapata',0.0,4,12,'00022_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Saletein Primus malbec','Saletein',0.0,5,12,'00028_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Jardin Echante','Jardin Echante',0.0,3,12,'00025_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Salentein Reserva Rosado','Saletein',0.0,5,12,'00024_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('La Posta Rosado','La Posta',0.0,3,12,'00026_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Piatelli Chardonnay Edition Limited ','Piatelli',0.0,3,12,'00029_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Cadus Vista Flores Appellation Chardonnay 750 ml','Cadus',0.0,3,12,'00030_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Animal Chardonnay Organico 750 ml','Animal',0.0,4,12,'00032_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Alamos Chardonnay 750 ml','Alamos ',0.0,4,12,'00031_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Victorino Torrontes 750 ml','Victorino Torrontes',0.0,4,12,'00034_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ruca Malen Chardonnay Terroir Series 750 ml','Ruca Malen',0.0,4,12,'00035_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Territorio Torrontes 750 ml','Territorio',0.0,3,12,'00033_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Portillo Dulce Natural 750 ml','Portillo',0.0,3,12,'00036_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Amalaya Gran Corte 750 ml','Amalaya',0.0,3,12,'00038_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Amalaya Corte Unico  750 ml','Amalaya',0.0,3,12,'00037_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Tikal Jubilo 2015 750 ml','Tikal',0.0,4,12,'00039_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Tikal Amorio 2015 750 ml','Tikal',0.0,4,12,'00040_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Bramare Lujan de Cuyo 2017 750 ml','Bramare Valle De Uco',0.0,4,12,'00041_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Salentein Corte de Tintas 750 ml','Salentein',0.0,5,12,'00043_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Salentein Corte de Blancas 750 ml','Salentein',0.0,5,12,'00042_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Petit Caro cabernet sauvignon malbec nicolas catena x 750 ml','Petit Caro',0.0,4,12,'00044_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Salentein Numina Malbec','Salentein',0.0,5,12,'00046_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Salentein Numina Cabernet Franc 750 ml','Salentein',0.0,5,12,'00045_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Salentein Late Harvest Sauvignon Blanc 500 ml','Salentein',0.0,5,12,'00047_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Escorihuela Gascon Pinot Noir','Escorihuela Gascon',0.0,4,12,'00020_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Padrillos Malbec 375  ml','Padrillos',0.0,3,12,'00027_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Domaine Grand Mere 2018','Domaine Nico Grand',0.0,4,12,'00023_VINOYCH','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Aberlour 12YO Estuche 700 ml','Aberlour ',0.0,5,10,'14','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Ballantines 1 Lts','Ballantines',0.0,5,10,'15','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Blenders Honey 750 ml','Blenders',0.0,5,10,'16','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Blenders 1 Lts','Blenders',0.0,5,10,'0021_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Blenders petaca 200 ml','Blenders',0.0,5,10,'0023_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Blenders 750 ml ','Blenders',0.0,5,10,'17','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Bruichladdich Classic Laddie Estuche 700 ml','Bruichladdich ',0.0,5,10,'19','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Chivas 12 años 500 ml','Chivas',0.0,5,10,'20','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Chivas 12 años 750 ml','Chivas',0.0,5,10,'21','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Chivas 12 años x 1000','Chivas',0.0,5,10,'0017_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Chivas 12 años de 1 Lts +  Chivas pequeñas 15 x 50 ml','Chivas',0.0,5,10,'24','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Chivas 15 años Dorado 750 ml','Chivas',0.0,5,10,'25','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Chivas Mizurana 750 ml','Chivas',0.0,5,10,'27','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Cutty Sark Blended Scotch Wisky 750 ml','Cutty Sark',0.0,5,10,'0018_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Dewars 12 estuche','Dewars',0.0,5,10,'28','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Glen Moray Chardonay 1 x 700 ml','Glen ',0.0,5,10,'30','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jack Daniels Honey 750 ml ','Jack Daniels',0.0,5,10,'31','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jameson Ipa 750 ml','Jameson',0.0,5,10,'32','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jameson Stout 750 ml','Jameson',0.0,5,10,'0020_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jameson 1000 cc','Jameson',0.0,5,10,'0022_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jameson 750 ml','Jameson',0.0,5,10,'33','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Macallan Highland Single Sherry Oak Cask 12 years','Macallan',0.0,5,10,'0019_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Old Smuggler 750 ml','Old',0.0,3,10,'35','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Port Charlotte 10 años estuche 700 ml','Port Charlotte ',0.0,5,10,'36','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Royal Salute 21 años 700 ml','Royal Salute',0.0,5,10,'38','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky The GlenLivet Single Malt','The GlenLivet ',0.0,5,10,'39','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky The Macallan 12 estuche 700 ml','The Macallan',0.0,5,10,'34','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Vat 69 750 ml','Vat 69',0.0,3,10,'40','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker green label estuche 750 ml','Johnnie Walker ',0.0,5,10,'0001_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker black label 12 años estuche 750 ml ','Johnnie Walker ',0.0,5,10,'0003_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker black label 12 años 1 litro','Johnnie Walker ',0.0,5,10,'0004_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker black label 12 años lata ','Johnnie Walker ',0.0,5,10,'0005_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker blue label estuche 750 ml','Johnnie Walker ',0.0,5,10,'0011_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker white walker 750 ml','Johnnie Walker ',0.0,5,10,'0014_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker Gold Label reserve 18 años estuche 750 ml','Johnnie Walker ',0.0,5,10,'0010_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker red label 750 ml','Johnnie Walker ',0.0,5,10,'0012_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Johnnie walker red label 1 litro estuche','Johnnie Walker ',0.0,5,10,'0013_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Wild turkey american 101 bourbon 750 ml','Wild Turket American ',0.0,5,10,'0015_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Wild turkey american honey 750 ml','Wild Turket American ',0.0,5,10,'0016_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jim beam honey 750 ml','Jim Beam',0.0,4,10,'0008_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jim beam bourbon 750 ml','Jiam Beam',0.0,4,10,'0006_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Jim beam vainilla 750 ml','Jiam Beam',0.0,4,10,'0009_whisky','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Whisky Ioch lomond original single malt 750 ml','Loch Lomond ',0.0,5,10,'41','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Country Of Sweden 1,75 lt','Absolut ',0.0,5,9,'0028_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Elyx 1 Lt','Absolut ',0.0,5,9,'0003_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Elyx 1,5 Lt','Absolut ',0.0,5,9,'0036_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Lime 750 cc','Absolut ',0.0,5,9,'0006_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut apple 750 ml','Absolut ',0.0,5,9,'0002_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Extracto Cardomo 750 ml','Absolut ',0.0,5,9,'0004_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Grapefruit 750 ml','Absolut ',0.0,5,9,'0005_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Mandarin 750 ml','Absolut ',0.0,5,9,'0007_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Mango ','Absolut ',0.0,5,9,'0008_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Apeach','Absolut ',0.0,5,9,'0001_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Raspberry','Absolut ',0.0,5,9,'0029_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Absolut Vainilla 750 ml','Absolut ',0.0,5,9,'0009_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Grey Goose Vodka x 375 ml','Gre Goose',0.0,5,9,'0010_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Nikov Mango 1 lt','Nikov',0.0,3,9,'0011_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Nikov Strong 1 lt','Nikov',0.0,3,9,'0012_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Nikov tradicional 1 lt','Nikov',0.0,3,9,'0030_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Pravda 750 ml','Pravda',0.0,5,9,'0013_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Sernova Fresh Citrus','Sernova',0.0,4,9,'0014_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Sernova Vodka Original ','Sernova',0.0,4,9,'0032_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Sernova Wild Berries ','Sernova',0.0,4,9,'0033_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Skyy Citrus ','Skyy',0.0,4,9,'0034_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Sky Coconout','Skyy',0.0,4,9,'0016_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Tito´s Handmade 50 ml','Tito's ',0.0,4,9,'0018_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Hiram Walker 1 lt','Hiram ',0.0,4,9,'0035_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Red 700ml','Smirnoff ',0.0,4,9,'0019_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Skyy','Skyy',0.0,4,9,'0022_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Skyy Passion Fruit ','Skyy',0.0,4,9,'0020_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Skyy Raspberry ','Skyy',0.0,4,9,'0021_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Smirnoff Citrus 700 ml','Smirnoff ',0.0,5,9,'0023_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Smirnoff Clasico 700 ml','Smirnoff ',0.0,5,9,'0024_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Smirnoff Green Apple 700 ml','Smirnoff ',0.0,5,9,'0025_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Smirnoff Raspberry ','Smirnoff ',0.0,5,9,'0026_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Smirnoff Watermelon 700 ml','Smirnoff ',0.0,5,9,'0027_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Vodka Smirnoff Bitter Citric 700 ml','Smirnoff ',0.0,5,9,'0017_vodka','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Bacardi Carta Blanca 1 lt','Bacardi',0.0,4,6,'2_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Bacardi Carta Blanca 750 ml','Bacardi',0.0,3,6,'3_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Bacardi Coca RTD lata 310 ml','Bacardi',0.0,2,6,'4_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Bacardi Dorado 750 ml','Bacardi',0.0,3,6,'5_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Bacardi Dorado 1 Lt','Bacardi',0.0,3,6,'6_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Bacardi Mojito RTD lata 310 ml','Bacardi',0.0,2,6,'14_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Captain Morgan Spiced Gold 700 ml','Captain Morgan',0.0,3,6,'7_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Coco Bongo Melon 750 ml','Coco Bongo',0.0,2,6,'9_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Havana 7 años 750 ml','Havana Club',0.0,4,6,'10_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Havana Club Añejo 3 años Blanco 750 ml','Havana Club ',0.0,4,6,'11_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Havana Club Añejo especial 200 ml petaca','Havana Club',0.0,4,6,'12_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Havana Club Añejo especial 750 ml','Havana Club',0.0,4,6,'13_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Ron Cayman Light x 200 ml Petaca','Cayman',0.0,2,6,'8_ron','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet 1882 x 750 ml','1882',0.0,5,3,'0001_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet Branca 1 Lt ','Fernet Branca',0.0,5,3,'0002_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet Branca 450 ml','Fernet Branca',0.0,5,3,'0003_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet Branca 750 ml','Fernet Branca',0.0,5,3,'0004_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet edición especial 3 lts','Fernet Branca',0.0,5,3,'0005_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet Menta 450 ml','Fernet Branca',0.0,5,3,'0006_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet Menta 750 ml ','Fernet Branca',0.0,5,3,'0007_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Fernet petaca','Fernet Branca',0.0,5,3,'0008_FERNET','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Tequila El Jimador 750 ml','El Jimador',0.0,2,8,'tequila.1','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Tequila Jose Cuervo Especial Dorado Blue Agave 750 ml','Jose Cuervo',0.0,3,8,'tequila.2','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Tequila Jose Cuervo Silver Blanco Blue Agave 750 ml','Jose Cuervo',0.0,3,8,'tequila.3','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Tequila Jose Cuervo Tradicional 100% Agave','Jose Cuervo',0.0,3,8,'tequila.4','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Sidra 1888 Rose 750 ml ','1888',0.0,3,7,'2_sidra','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Sidra 1888 750 ml','1888',0.0,3,7,'1_sidra','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Sidra Pehuenia Dulce 500 ml','Pehuenia',0.0,2,7,'3_sidra','jpg',74);
INSERT INTO product (description,name,price,rating,category,imagen,ext,store) VALUE('Sidra Pehuenia Jengibre 500 ml','Pehuenia',0.0,2,7,'4_sidra','jpg',74);