SELECT 
emp.W05CUI AS CUIT,
emp.W05DER AS RAZONSOCIAL,
conv.ID AS CONVENIO_ID,
tip_conv.DESCRIPCION TIPOCONVENIO,
tip_conv.CANTIDAD_CUOTAS AS CANT_CUOTAS,
conv.SALDO AS SALDO,
conv.IMPORTE_CUOTA AS IMPORTE_COUTA,
conv.DEUDA_TOTAL AS TOTAL_DEUDA,
estado_conv.DESCRIPCION AS ESTADO,
(SELECT MIN(DATE(FECHA_VENCIMIENTO)) FROM APORTES.CONVENIO_CUOTA WHERE CONVENIO_ID = conv.ID) AS PRIMERVENCIMIENTO,
(SELECT MAX(DATE(FECHA_VENCIMIENTO)) FROM APORTES.CONVENIO_CUOTA WHERE CONVENIO_ID = conv.ID) AS ULTIMOVENCIMIENTO,
DATE(conv.FECHA_SIS) AS FECHA, 
conv.GESTOR_ID AS GESTOR_ID, 
gest.DESCRIPCION AS GESTOR_NOMBR
cuota.IMPORTE AS SALDO_IMPORTE_CUOTA
cuota.IMPORTE_SIN_INTERESES AS IMPORTE_SIN_INTERESES_CUOTA
cuota.INTERESES AS INTERESES_CUOTA
FROM APORTES.CONVENIO conv
LEFT JOIN APORTES.ESTADO_CONVENIO estado_conv ON estado_conv.ID = conv.ESTADO 
LEFT JOIN APORTES.TIPO_CONVENIO tip_conv ON tip_conv.ID = conv.TIPO_CONVENIO
LEFT JOIN SMPLIBD.M05FEMP emp ON conv.CUIT = emp.W05CUI
LEFT JOIN MORA.MORA_EMPRESA_GESTORES gest ON gest.USUARIO_ID = conv.GESTOR_ID
LEFT JOIN APORTES.CONVENIO_CUOTA cuota ON cuota.CONVENIO_ID = conv.ID;